[[redirects]]
  from = "/api/v3/invoices"
  to = "https://invoice.zoho.com"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "/*"
  to = "https://eloquent-allen-da04f5.netlify.app/index.html"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}