[[redirects]]
  from = "/api/*"
  to = "https://invoice.zoho.in/:splat"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}



  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
