[[redirects]]
  from = "/api/v3/invoices/"
  to = "https://invoice.zoho.in"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "/api/v3/contacts/"
  to = "https://invoice.zoho.in"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
