[[redirects]]
  from = "https://eloquent-allen-da04f5.netlify.app/api/v3/invoices"
  to = "https://invoice.zoho.in/api/v3/invoices/"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "https://eloquent-allen-da04f5.netlify.app/api/v3/contacts"
  to = "https://invoice.zoho.in/api/v3/contacts/"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}

  [redirects]]
  from = "https://eloquent-allen-da04f5.netlify.app/api/v3/invoices/*"
  to = "https://invoice.zoho.in/api/v3/invoices/:splat"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "https://eloquent-allen-da04f5.netlify.app/api/v3/contacts/*"
  to = "https://invoice.zoho.in/api/v3/contacts/:splat"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
